
# TODO: too tolerant

coverage:
  range: '0...60' # custom range of coverage colors from red -> yellow -> green
  round: down     # how coverage is rounded: down/up/nearest
  precision: 2    # how many decimal places to display in the UI: 0 <= value <= 4
  status:
    project:      # measuring the overall project coverage
      default:
        target: 60%    # the target coverage for each commit status
        threshold: 5%  # allowed to drop X% and still result in a "success" commit status
    patch:        # measures how well the lines diffed in a PR are tested
      default:
        target: 60%
        threshold: 5%
