linters:
  enable-all: true
  disable:
    - wrapcheck
    - paralleltest
    - gomnd
    - wsl
    - nlreturn
    - goerr113
    - gci
      # disabled in golangci-lint v1.45.2 due to 1.18
    - bodyclose
    - contextcheck
    - gosimple
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tparallel
    - unparam
    - wastedassign
    - unused
      # deprecated
    - interfacer
    - maligned
    - scopelint
    - golint
    - exhaustivestruct # since v1.46.0
    - execinquery # panics in v1.46.1; the fix is merged https://github.com/lufeee/execinquery/pull/13

linters-settings:
  cyclop:
    max-complexity: 20
  funlen:
    lines: 100
  gocognit:
    min-complexity: 40
  lll:
    line-length: 160
  goimports:
    local-prefixes: github.com/michurin/netpunch
  varnamelen:
    max-distance: 16

issues:
  exclude-rules:
    - path: cmd/netpunch/main.go
      linters:
        - gochecknoinits
        - gochecknoglobals
        - forbidigo
