linters:
  enable-all: true
  disable:
      # nice to be turned on
    - wsl
    - nlreturn
    - err113
    - mnd
    - wrapcheck
      # deprecated
    - exportloopref
      # disabled because the Go version
    - copyloopvar
    - intrange

linters-settings:
  paralleltest:
    ignore-missing: true
  cyclop:
    max-complexity: 20
  funlen:
    lines: 100
  gocognit:
    min-complexity: 40
  lll:
    line-length: 160
  goimports:
    local-prefixes: github.com/michurin/netpunch
  varnamelen:
    max-distance: 16
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/michurin/netpunch/netpunchlib)
  depguard:
    rules:
      regular:
        files:
          - !$test
        allow:
          - $gostd
          - github.com/michurin/netpunch/netpunchlib
      tests:
        files:
          - $test
        allow:
          - $gostd
          - github.com/michurin/netpunch/netpunchlib
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - github.com/golang/mock/gomock

issues:
  exclude-rules:
    - path: cmd/netpunch/main.go
      linters:
        - gochecknoinits
        - gochecknoglobals
        - forbidigo
