version: "2"
linters:
  default: all
  disable:
    - copyloopvar
    - err113
    - intrange
    - mnd
    - nlreturn
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    depguard:
      rules:
        regular:
          files:
            - ""
          allow:
            - $gostd
            - github.com/michurin/netpunch/netpunchlib
        tests:
          files:
            - $test
          allow:
            - $gostd
            - github.com/michurin/netpunch/netpunchlib
            - github.com/stretchr/testify/assert
            - github.com/stretchr/testify/require
            - go.uber.org/mock/gomock
    funlen:
      lines: 100
    gocognit:
      min-complexity: 40
    lll:
      line-length: 160
    paralleltest:
      ignore-missing: true
    varnamelen:
      max-distance: 16
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
          - gochecknoglobals
          - gochecknoinits
        path: cmd/netpunch/main.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/michurin/netpunch/netpunchlib)
    goimports:
      local-prefixes:
        - github.com/michurin/netpunch
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
