---
name: build # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.16"
          - "1.17"
          - "1.18"
    name: "Go ${{ matrix.go }} build"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go }}"
      - run: "go version"
      - run: "test ! -e netpunch"
      - run: "./build.sh -b"
      - run: "test -e netpunch"
  test:
    runs-on: ubuntu-latest
    name: "Test and lint"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.45"
      - run: "go test ./..."
