---
name: build # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
    name: "Go ${{ matrix.go }} build"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"
      - run: "go version"
      - run: "test ! -e netpunch"
      - run: "./build.sh -b"
      - run: "test -e netpunch"
  test:
    runs-on: ubuntu-latest
    name: "Test and lint"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.54"
      - run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ./netpunchlib/..."
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          verbose: true
