---
name: build # this string appears on badge
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    name: "Go ${{ matrix.go }} build"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
      - run: "go version"
      - run: "test ! -e netpunch"
      - run: "./build.sh -b"
      - run: "test -e netpunch"
  test:
    runs-on: ubuntu-latest
    name: "Test and lint"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.62"
      - run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./netpunchlib/... ./netpunchlib/..."
      - run: "grep -v netpunchlib/internal/mock/connection.go coverage.txt >coverage-clean.txt"
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          disable_search: true # to skip interim coverage files
          files: ./coverage-clean.txt
          verbose: true
